name: RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Test
        run: |
          Write-Host "Windows runner started"
          Start-Sleep -Seconds 30
