name: RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Test Windows
        run: |
          Write-Host "Windows Runner Started"
          systeminfo
          Start-Sleep -Seconds 60
